# Generated by Django 4.2.4 on 2023-09-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_guestuser_rename_userprofile_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestuser',
            old_name='user_session',
            new_name='session',
        ),
    ]
