# Generated by Django 4.2.4 on 2023-09-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dummy',
            field=models.CharField(default='Mani', max_length=255),
        ),
    ]
