# Generated by Django 4.2.4 on 2023-09-23 05:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='IN', unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
