# Generated by Django 4.2.4 on 2023-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_offer_product_offers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, to='shop.offer'),
        ),
    ]
